// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.Scanner;
import java.util.Vector;

/************************************************************/
/**
 * 
 */
public class Client extends tema2_ISP.User {
	public Client(String email_user, String parola, String tip_utilizator) {
		super(email_user, parola, tip_utilizator);
		if(tip_utilizator == "CLIENT_L") {
			super.logat = super.login(email_user, parola);
			super.afisareUser();
			System.out.println("V-ati logat cu urmatoarele date:");
			while(true) {
				this.loadPossibilities();
			}
		}
		else if(tip_utilizator == "GUEST") {
			System.out.println("Bun venit pe aplicatia noastra!");
			this.afisareUser();
			while(true) {
				this.loadPossibilities();
			}
		}
		else if(tip_utilizator == "CLIENT_C") {
			super.create_account();
			super.logat = super.login(email_user, parola);
		}
	}
	public String error_status = "";
	
	void loadPossibilities() {
		System.out.println("Aveti posibilitatea urmatoarelor operatii:");
		System.out.println("1.Schimbare username");
		System.out.println("2.Schimbare parola");
		System.out.println("3.Logout");
		System.out.println("4.Generare comanda");
		System.out.println("5.Vizualizari istoric comenzi");
		BufferedReader input_client = new BufferedReader(new InputStreamReader (System.in));
		String optiune_client;
		try {
			    optiune_client = new String(input_client.readLine());
				switch(optiune_client) {
				case "1":{
					BufferedReader input_new_username= new BufferedReader(new InputStreamReader (System.in));
					System.out.println("Introduceti noul username: ");
					try {
						String new_username = new String(input_new_username.readLine());
						super.change_username(new_username);
					}
					catch(IOException e1) {
						e1.printStackTrace();
					}	
					break;
					
				}
				case "2":{
					System.out.println("Introduceti noua parola:");
					BufferedReader input_new_parola= new BufferedReader(new InputStreamReader (System.in));
					try {
						String new_pass = new String(input_new_parola.readLine());
						super.setPass(new_pass);
					}
					catch(IOException e1) {
						e1.printStackTrace();
					}	
					break;
				}
				case "3":{
					super.logout();
					break;
				}
				case "4":{
					//ETAPA 1: Afisarea ofertelor
					this.afisareOferte();
					if(oferteVizualizate.size() == 0) {
						System.err.println("Nu puteti vizualiza oferte intrucat nu exista oferte!");
						this.error_status = "Nu puteti vizualiza oferte intrucat nu exista oferte!";
						break;
					}
					else {
						//ETAPA 2: SELECTAREA CATEGORIEI DE OFERTA
						this.error_status = "";
						String tip_comanda = "";
						System.out.println("Alegeti tipul de oferta dorit[M-Masina,A-Avion,H-Hotel]:");
						BufferedReader input_tip_comanda= new BufferedReader(new InputStreamReader (System.in));
						try {
							 tip_comanda = new String(input_tip_comanda.readLine());
						}
						catch(IOException e1) {
							e1.printStackTrace();
						}	
						
						//ETAPA 3.1: FILTRAREA OFERTELOR IN FCT DE CRITERIILE SPECIFICE FIECAREI CATEGORII DE OFERTA
						switch(tip_comanda) {
							case "A":{
								if(this.oferteVizualizateBiletAvion.size()!=0) {
								this.afisareOferteBiletAvion();
									//FILTRE AVION (Destinatie,Ora_decolare,Pret,Clasa,nrEscale)
									System.out.println("Doriti sa filtrati ofertele de bilete de avion ?[y/n]");
									String continuare = "";
									BufferedReader get_cont= new BufferedReader(new InputStreamReader (System.in));
									try {
										continuare = new String(get_cont.readLine());
									}
									catch(IOException e1) {
										e1.printStackTrace();
									}
									if(continuare.equals("y")) {
										System.out.println("Exista urmatoarele optiuni de filtrare pentru bilete de avion:");
										System.out.println("1.Pret maxim/Ora dorit");
										System.out.println("2.Ora Decolare");
										System.out.println("3.Clasa zbor");
										System.out.println("4.Destinatie");
										System.out.println("5.Numar Escale");
										
										//Eventual daca se mai vrea , implementam toate combiantiile posibile
										String input_filtrare = "";
										BufferedReader get_filter= new BufferedReader(new InputStreamReader (System.in));
										try {
											input_filtrare = new String(get_filter.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										
										Vector<tema2_ISP.OferteBiletAvion> vec_avioane_filtrate = null;
										//Implementare filtrarilor
										switch(input_filtrare) {
											case "1":{
												
												vec_avioane_filtrate = this.afisareOferteBiletAvionFiltrat(tema2_ISP.FiltreAvion.Pret);
												break;
											}
											case "2":{
												vec_avioane_filtrate = this.afisareOferteBiletAvionFiltrat(tema2_ISP.FiltreAvion.Ora);
												break;
											}
											case "3":{
												vec_avioane_filtrate = this.afisareOferteBiletAvionFiltrat(tema2_ISP.FiltreAvion.Clasa);
												break;
											}
											case "4":{
												vec_avioane_filtrate = this.afisareOferteBiletAvionFiltrat(tema2_ISP.FiltreAvion.Destinatie);
												break;
											}
											case "5":{
												vec_avioane_filtrate = this.afisareOferteBiletAvionFiltrat(tema2_ISP.FiltreAvion.NrEscale);
												break;
											}
										}
										//Afisare oferte filtrate
										Iterator<tema2_ISP.OferteBiletAvion> oferte_avioane_filtrate = vec_avioane_filtrate.iterator();
										while(oferte_avioane_filtrate.hasNext()) {
											((tema2_ISP.OferteBiletAvion) oferte_avioane_filtrate.next()).generareDetaliiIncluse(); 
										}
										
										//SELECTARE OFERTA SAU BACK
										System.out.println("Doriti sa selectati vreo oferta de bilet avion?[y/n]");
										String cont1 = "";
										BufferedReader get_cont1= new BufferedReader(new InputStreamReader (System.in));
										try {
											cont1 = new String(get_cont1.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										if(cont1.contentEquals("y")){
											
											System.out.println("Aveti 2 optiuni:");
											System.out.println("1. Afisare detalii despre o oferta. ");
											System.out.println("2. Comanda oferta. ");
											String opt = "";
											BufferedReader get_cont2= new BufferedReader(new InputStreamReader (System.in));
											try {
												opt = new String(get_cont2.readLine());
											}
											catch(IOException e1) {
												e1.printStackTrace();
											}
											//SELECTIE OFERTA USER
											System.out.println("Introduceti codul ofertei dorite.");
											String cod_oferta = "";
											BufferedReader get_cod= new BufferedReader(new InputStreamReader (System.in));
											try {
												cod_oferta = new String(get_cod.readLine());
											}
											catch(IOException e1) {
												e1.printStackTrace();
											}
											this.selectareDetaliiSauInitiereComanda(cod_oferta, "A", opt);								
										}
										else {
											vec_avioane_filtrate.clear();
										}
										
										
									}
									else {
										System.out.println("Aveti 2 optiuni:");
										System.out.println("1. Afisare detalii despre o oferta. ");
										System.out.println("2. Comanda oferta. ");
										String opt = "";
										BufferedReader get_cont2= new BufferedReader(new InputStreamReader (System.in));
										try {
											opt = new String(get_cont2.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										//SELECTIE OFERTA USER
										System.out.println("Introduceti codul ofertei dorite.");
										String cod_oferta = "";
										BufferedReader get_cod= new BufferedReader(new InputStreamReader (System.in));
										try {
											cod_oferta = new String(get_cod.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										this.selectareDetaliiSauInitiereComanda(cod_oferta, "A", opt);	
									}
									break;
								}
								else {
									System.err.println("Nu exista oferte de acest tip!");
									break;
								}
							}
							case "H":{
								if(this.oferteVizualizateSejurHotel.size()!=0) {
									this.afisareOferteSejurHotel();
									//Filtrari Hotel(TipCamera,Facilitati,Pret,Locatie)
									System.out.println("Doriti sa filtrati ofertele de sejur hotel ?[y/n]");
									String continuare = "";
									BufferedReader get_cont= new BufferedReader(new InputStreamReader (System.in));
									try {
										continuare = new String(get_cont.readLine());
									}
									catch(IOException e1) {
										e1.printStackTrace();
									}
									if(continuare.equals("y")) {
										System.out.println("Exista urmatoarele optiuni de filtrare pentru bilete de avion:");
										System.out.println("1.Pret maxim dorit pe nrZile dorit");
										System.out.println("2.Tipul De Camera");
										System.out.println("3.Facilitati");
										System.out.println("4.Locatie Hotel");
										
										//Eventual daca se mai vrea , implementam toate combiantiile posibile
										String input_filtrare = "";
										BufferedReader get_filter= new BufferedReader(new InputStreamReader (System.in));
										try {
											input_filtrare = new String(get_filter.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										
										Vector<tema2_ISP.OferteSejurHotel> vec_hotele_filtrate = null;
										//Implementare filtrarilor
										switch(input_filtrare) {
											case "1":{
												
												vec_hotele_filtrate = this.afisareOferteHoteleFiltrate(tema2_ISP.FiltreHotel.Pret);
												break;
											}
											case "2":{
												vec_hotele_filtrate = this.afisareOferteHoteleFiltrate(tema2_ISP.FiltreHotel.TipCamera);
												break;
											}
											case "3":{
												vec_hotele_filtrate = this.afisareOferteHoteleFiltrate(tema2_ISP.FiltreHotel.Facilitati);
												break;
											}
											case "4":{
												vec_hotele_filtrate = this.afisareOferteHoteleFiltrate(tema2_ISP.FiltreHotel.Locatie);
											}
										}
										
										
										//Afisare oferte filtrate
										Iterator<tema2_ISP.OferteSejurHotel> oferte_hotele_filtrate = vec_hotele_filtrate.iterator();
										while(oferte_hotele_filtrate.hasNext()) {
											((tema2_ISP.OferteSejurHotel) oferte_hotele_filtrate.next()).generareDetaliiIncluse(); 
										}
										
										//SELECTARE OFERTA SAU BACK
										System.out.println("Doriti sa selectati vreo oferta de bilet avion?[y/n]");
										String cont1 = "";
										BufferedReader get_cont1= new BufferedReader(new InputStreamReader (System.in));
										try {
											cont1 = new String(get_cont1.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										if(cont1.contentEquals("y")){
											
											
											System.out.println("Aveti 2 optiuni:");
											System.out.println("1. Afisare detalii despre o oferta. ");
											System.out.println("2. Comanda oferta. ");
											String opt = "";
											BufferedReader get_cont2= new BufferedReader(new InputStreamReader (System.in));
											try {
												opt = new String(get_cont2.readLine());
											}
											catch(IOException e1) {
												e1.printStackTrace();
											}
											//SELECTIE OFERTA USER
											System.out.println("Introduceti codul ofertei dorite.");
											String cod_oferta = "";
											BufferedReader get_cod= new BufferedReader(new InputStreamReader (System.in));
											try {
												cod_oferta = new String(get_cod.readLine());
											}
											catch(IOException e1) {
												e1.printStackTrace();
											}
											this.selectareDetaliiSauInitiereComanda(cod_oferta, "H", opt);	
										}
										else {
											vec_hotele_filtrate.clear();
										}
										
									}
									else {
										System.out.println("Aveti 2 optiuni:");
										System.out.println("1. Afisare detalii despre o oferta. ");
										System.out.println("2. Comanda oferta. ");
										String opt = "";
										BufferedReader get_cont2= new BufferedReader(new InputStreamReader (System.in));
										try {
											opt = new String(get_cont2.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										//SELECTIE OFERTA USER
										System.out.println("Introduceti codul ofertei dorite.");
										String cod_oferta = "";
										BufferedReader get_cod= new BufferedReader(new InputStreamReader (System.in));
										try {
											cod_oferta = new String(get_cod.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										this.selectareDetaliiSauInitiereComanda(cod_oferta, "H", opt);
									}
									break;

								}
								else {
									System.err.println("Nu exista oferte de acest tip!");
									break;
								}
							}
							case "M":{
								if(this.oferteVizualizateMasini.size()!=0) {
									this.afisareOferteMasini();
									//SELECTARE DESTINATIE
									String destinatie_comanda = "";
									System.out.println("Introduceti destinatia la care doriti sa ajungeti:");
									BufferedReader getDestinatie= new BufferedReader(new InputStreamReader (System.in));
									try {
										destinatie_comanda = new String(getDestinatie.readLine());
									}
									catch(IOException e1) {
										e1.printStackTrace();
									}
									this.setDestinatie_curenta(destinatie_comanda);
									//FILTRARI MASINI							
									System.out.println("Doriti sa filtrati ofertele de masini?[y/n]");
									String continuare = "";
									BufferedReader get_cont= new BufferedReader(new InputStreamReader (System.in));
									try {
										continuare = new String(get_cont.readLine());
									}
									catch(IOException e1) {
										e1.printStackTrace();
									}
									if(continuare.equals("y")) {
										System.out.println("Exista urmatoarele optiuni de filtrare pentru masini:");
										System.out.println("1.Pret maxim/Ora dorit");
										System.out.println("2.Nr Locuri Masina");
										System.out.println("3.Marca");
										
										//Eventual daca se mai vrea , implementam toate combiantiile posibile
										String input_filtrare = "";
										BufferedReader get_filter= new BufferedReader(new InputStreamReader (System.in));
										try {
											input_filtrare = new String(get_filter.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										Vector<tema2_ISP.OferteMasini> vec_masini_filtrate = null;
										//Implementarea filtrarilor
										switch(input_filtrare) {
											case "1":{
												
												vec_masini_filtrate = this.afisareOferteMasiniFiltrate(tema2_ISP.FiltreMasini.Pret);
												break;
											}
											case "2":{
												vec_masini_filtrate = this.afisareOferteMasiniFiltrate(tema2_ISP.FiltreMasini.NrLocuri);
												break;
											}
											case "3":{
												vec_masini_filtrate = this.afisareOferteMasiniFiltrate(tema2_ISP.FiltreMasini.Marca);
												break;
											}
										}
										
										//Afisare oferte filtrate
										Iterator<tema2_ISP.OferteMasini> oferte_masini_filtrate = vec_masini_filtrate.iterator();
										while(oferte_masini_filtrate.hasNext()) {
											((tema2_ISP.OferteMasini) oferte_masini_filtrate.next()).generareDetaliiIncluse(); 
										}
										
										//SELECTARE OFERTA SAU BACK
										System.out.println("Doriti sa selectati vreo oferta de masini?[y/n]");
										String cont1 = "";
										BufferedReader get_cont1= new BufferedReader(new InputStreamReader (System.in));
										try {
											cont1 = new String(get_cont1.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										if(cont1.contentEquals("y")){
											System.out.println("Aveti 2 optiuni:");
											System.out.println("1. Afisare detalii despre o oferta. ");
											System.out.println("2. Comanda oferta. ");
											String opt = "";
											BufferedReader get_cont2= new BufferedReader(new InputStreamReader (System.in));
											try {
												opt = new String(get_cont2.readLine());
											}
											catch(IOException e1) {
												e1.printStackTrace();
											}
											//SELECTIE OFERTA USER
											System.out.println("Introduceti codul ofertei dorite.");
											String cod_oferta = "";
											BufferedReader get_cod= new BufferedReader(new InputStreamReader (System.in));
											try {
												cod_oferta = new String(get_cod.readLine());
											}
											catch(IOException e1) {
												e1.printStackTrace();
											}
											this.selectareDetaliiSauInitiereComanda(cod_oferta, "M", opt);
										}
										else {
											vec_masini_filtrate.clear();
										}
										
										
									}
									else {
										System.out.println("Aveti 2 optiuni:");
										System.out.println("1. Afisare detalii despre o oferta. ");
										System.out.println("2. Comanda oferta. ");
										String opt = "";
										BufferedReader get_cont2= new BufferedReader(new InputStreamReader (System.in));
										try {
											opt = new String(get_cont2.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										//SELECTIE OFERTA USER
										System.out.println("Introduceti codul ofertei dorite.");
										String cod_oferta = "";
										BufferedReader get_cod= new BufferedReader(new InputStreamReader (System.in));
										try {
											cod_oferta = new String(get_cod.readLine());
										}
										catch(IOException e1) {
											e1.printStackTrace();
										}
										this.selectareDetaliiSauInitiereComanda(cod_oferta, "M", opt);
									}
									break;
								}
								else {
									System.err.println("Nu exista oferte de acest tip!");
									break;
								}
							}
							default:{
								System.out.println("Nu ati ales o categorie valida de oferte!");
								break;
							}
						}
						break;
						
					}
				}
				case "5":{
					//SPECIFICA CLIENTULUI 
					this.vizualizareIstoricRezervari();
					break;
				}
				default:{
					super.exit();
					break;
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	/**
	 * 
	 */
	private tema2_ISP.Categorie_Oferta current_selection;
	/**
	 * 
	 */
	private float pret_comanda_curenta;
	/**
	 * 
	 * @param cod_comanda 
	 */
	private String destinatie_curenta;
	public Vector<tema2_ISP.Oferte> oferteVizualizate  = tema2_ISP.Administrator.oferte;
	public Vector<OferteMasini> oferteVizualizateMasini  = tema2_ISP.Administrator.oferteMasini;
	public Vector<OferteBiletAvion> oferteVizualizateBiletAvion  = tema2_ISP.Administrator.oferteAvion;
	public Vector<OferteSejurHotel> oferteVizualizateSejurHotel  = tema2_ISP.Administrator.oferteHotele;
	
	
	public void afisareOferte() {
		// Creating an iterator 
        Iterator<Oferte> value = oferteVizualizate.iterator(); 
        // Displaying the values 
        // after iterating through the vector 
        System.out.println("Toate ofertele curente: "); 
        while (value.hasNext()) { 
           ((Oferte) value.next()).generareDetaliiIncluse(); 
        } 
	}
	
	
	public void afisareOferteMasini() {
			Iterator<OferteMasini> value = oferteVizualizateMasini.iterator(); 
	        // Displaying the values 
	        // after iterating through the vector 
	        System.out.println("Toate ofertele de masini: "); 
	        while (value.hasNext()) { 
	        	 ((OferteMasini) value.next()).generareDetaliiIncluse();
	        } 
	}
	public void afisareOferteBiletAvion() {
			Iterator<OferteBiletAvion> value = oferteVizualizateBiletAvion.iterator(); 
	        // Displaying the values 
	        // after iterating through the vector 
	        System.out.println("Toate ofertele de bilete de avion: "); 
	        while (value.hasNext()) { 
	        	((OferteBiletAvion) value.next()).generareDetaliiIncluse();
	        } 
	}
	public void afisareOferteSejurHotel() {
			Iterator<OferteSejurHotel> value = oferteVizualizateSejurHotel.iterator(); 
	        // Displaying the values 
	        // after iterating through the vector 
	        System.out.println("Toate ofertele de sejur hotel: "); 
	        while (value.hasNext()) { 
	        	((OferteSejurHotel) value.next()).generareDetaliiIncluse();
	        }
	}
	
	public Vector<tema2_ISP.OferteMasini> afisareOferteMasiniFiltrate(tema2_ISP.FiltreMasini filtru_masina) {
		
		if(filtru_masina == tema2_ISP.FiltreMasini.Marca) {
			Vector<tema2_ISP.OferteMasini> vec_masini = new Vector<tema2_ISP.OferteMasini>();
			String marca_filtrare = "";
			System.out.println("Intruduceti va rog marca dorita:");
			Scanner scanner = new Scanner(System.in);
			marca_filtrare = scanner.nextLine();
			
			if(marca_filtrare.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteMasini> enumobject = oferteVizualizateMasini.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getMarca().equals(marca_filtrare)) {
	            		vec_masini.add(oferteVizualizateMasini.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_masini;
		}
		else if(filtru_masina == tema2_ISP.FiltreMasini.NrLocuri) {
			Vector<tema2_ISP.OferteMasini> vec_masini = new Vector<tema2_ISP.OferteMasini>();
			String nrLocuri = "";
			System.out.println("Intruduceti va rog nr de locuri dorite:");
			Scanner scanner = new Scanner(System.in);
			nrLocuri = scanner.nextLine();
			
			if(nrLocuri.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteMasini> enumobject = oferteVizualizateMasini.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getNrLocuri() == Integer.parseInt(nrLocuri)) {
	            		vec_masini.add(oferteVizualizateMasini.get(index));
	            	}
	        		index++;
	             }   
			}
			return vec_masini;
		}
		else if(filtru_masina == tema2_ISP.FiltreMasini.Pret) {
			
			Vector<tema2_ISP.OferteMasini> vec_masini = new Vector<tema2_ISP.OferteMasini>();
			String pret_per_zi = "";
			System.out.println("Intruduceti va rog preul/ora dorit:");
			Scanner scanner = new Scanner(System.in);
			pret_per_zi = scanner.nextLine();
			if(pret_per_zi.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteMasini> enumobject = oferteVizualizateMasini.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getNrLocuri() == Float.parseFloat(pret_per_zi)) {
	            		vec_masini.add(oferteVizualizateMasini.get(index));
	            	}
	        		index++;
	             }   
			}
			return vec_masini;
		}
		System.out.println("Masini filtrate");
		return oferteVizualizateMasini;
	}
	
	
	public Vector<tema2_ISP.OferteBiletAvion> afisareOferteBiletAvionFiltrat(tema2_ISP.FiltreAvion filtru_avion) {
		if(filtru_avion == tema2_ISP.FiltreAvion.Ora) {
			
			Vector<tema2_ISP.OferteBiletAvion> vec_avioane = new Vector<tema2_ISP.OferteBiletAvion>();
			String ora_filtrare = "";
			System.out.println("Intruduceti va rog ora de plecare dorita:");
			Scanner scanner = new Scanner(System.in);
			ora_filtrare = scanner.nextLine();
			if(ora_filtrare.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteBiletAvion> enumobject = oferteVizualizateBiletAvion.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getOra_decolare().equals(ora_filtrare)) {
	            		vec_avioane.add(oferteVizualizateBiletAvion.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_avioane;
		}
		else if(filtru_avion == tema2_ISP.FiltreAvion.Pret) {
			
			Vector<tema2_ISP.OferteBiletAvion> vec_avioane = new Vector<tema2_ISP.OferteBiletAvion>();
			String pret_filtrare = "";
			System.out.println("Intruduceti va rog pretul de bilet dorit:");
			Scanner scanner = new Scanner(System.in);
			pret_filtrare = scanner.nextLine();
			if(pret_filtrare.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteBiletAvion> enumobject = oferteVizualizateBiletAvion.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().Pret == Float.parseFloat(pret_filtrare)) {
	            		vec_avioane.add(oferteVizualizateBiletAvion.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_avioane;
			
		}
		else if(filtru_avion == tema2_ISP.FiltreAvion.Clasa) {
			Vector<tema2_ISP.OferteBiletAvion> vec_avioane = new Vector<tema2_ISP.OferteBiletAvion>();
			String clasa = "";
			System.out.println("Intruduceti va rog clasa dorit:");
			Scanner scanner = new Scanner(System.in);
			clasa = scanner.nextLine();
			if(clasa.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteBiletAvion> enumobject = oferteVizualizateBiletAvion.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getClasa_zbor().equals(clasa)) {
	            		vec_avioane.add(oferteVizualizateBiletAvion.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_avioane;
		}
		else if(filtru_avion == tema2_ISP.FiltreAvion.NrEscale) {
			Vector<tema2_ISP.OferteBiletAvion> vec_avioane = new Vector<tema2_ISP.OferteBiletAvion>();
			String nrEscale = "";
			System.out.println("Intruduceti va rog clasa dorit:");
			Scanner scanner = new Scanner(System.in);
			nrEscale = scanner.nextLine();
			
			if(nrEscale.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteBiletAvion> enumobject = oferteVizualizateBiletAvion.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getNrEscale() == Integer.parseInt(nrEscale)) {
	            		vec_avioane.add(oferteVizualizateBiletAvion.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_avioane;
		}
		else if(filtru_avion == tema2_ISP.FiltreAvion.Destinatie) {
			Vector<tema2_ISP.OferteBiletAvion> vec_avioane = new Vector<tema2_ISP.OferteBiletAvion>();
			String destinatie = "";
			Scanner scanner = new Scanner(System.in);
			destinatie = scanner.nextLine();
			if(destinatie.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteBiletAvion> enumobject = oferteVizualizateBiletAvion.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getDestinatie().equals(destinatie)) {
	            		vec_avioane.add(oferteVizualizateBiletAvion.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_avioane;
		}
		System.out.println("Bilete de avion filtrate");
		return oferteVizualizateBiletAvion;
	}
	
	
	public Vector<tema2_ISP.OferteSejurHotel> afisareOferteHoteleFiltrate(tema2_ISP.FiltreHotel filtru_hotel) {
		if(filtru_hotel == tema2_ISP.FiltreHotel.TipCamera) {
			
			Vector<tema2_ISP.OferteSejurHotel> vec_hotele = new Vector<tema2_ISP.OferteSejurHotel>();
			String tip_camera = "";
			System.out.println("Intruduceti va rog tipul de camera dorita:");
			Scanner scanner = new Scanner(System.in);
			tip_camera = scanner.nextLine();
			if(tip_camera.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteSejurHotel> enumobject = oferteVizualizateSejurHotel.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getTipCamera().equals(tip_camera)) {
	            		vec_hotele.add(oferteVizualizateSejurHotel.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_hotele;
		}
		else if(filtru_hotel == tema2_ISP.FiltreHotel.Facilitati){
			Vector<tema2_ISP.OferteSejurHotel> vec_hotele = new Vector<tema2_ISP.OferteSejurHotel>();
			String facilitati = "";
			System.out.println("Intruduceti va rog facilitatea dorita:");
			Scanner scanner = new Scanner(System.in);
			facilitati = scanner.nextLine();
			if(facilitati.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteSejurHotel> enumobject = oferteVizualizateSejurHotel.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getFacilitati().toLowerCase().contains(facilitati.toLowerCase())) {
	            		vec_hotele.add(oferteVizualizateSejurHotel.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_hotele;
		}
		else if(filtru_hotel == tema2_ISP.FiltreHotel.Pret) {
			Vector<tema2_ISP.OferteSejurHotel> vec_hotele = new Vector<tema2_ISP.OferteSejurHotel>();
			String pret = "";
			System.out.println("Intruduceti va rog pretul pe zi dorit:");
			Scanner scanner = new Scanner(System.in);
			pret = scanner.nextLine();
			if(pret.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteSejurHotel> enumobject = oferteVizualizateSejurHotel.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().Pret == Float.parseFloat(pret)) {
	            		vec_hotele.add(oferteVizualizateSejurHotel.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_hotele;
		}
		else if(filtru_hotel == tema2_ISP.FiltreHotel.Locatie) {
			Vector<tema2_ISP.OferteSejurHotel> vec_hotele = new Vector<tema2_ISP.OferteSejurHotel>();
			String locatie_hotel = "";
			System.out.println("Intruduceti va rog pretul pe zi dorit:");
			Scanner scanner = new Scanner(System.in);
			locatie_hotel = scanner.nextLine();
			if(locatie_hotel.contentEquals("") == false) {
	       		 System.out.println("Rezultatele cautarii dvs sunt urmatoarele:");
	       		 	
	       		 Enumeration<tema2_ISP.OferteSejurHotel> enumobject = oferteVizualizateSejurHotel.elements();  
	             int index = 0;
	             
	             while (enumobject.hasMoreElements())   
	             {             
	            	if(enumobject.nextElement().getLocatie().equals(locatie_hotel)) {
	            		vec_hotele.add(oferteVizualizateSejurHotel.get(index));
	            	}
	        		index++;
	             }   
			}
			
			return vec_hotele;
		}
		System.out.println("Hotele filtrate");
		return oferteVizualizateSejurHotel;
	}
	
	void selectareDetaliiSauInitiereComanda(String cod_oferta,String tip_comanda,String actiune) {
		//1A,2A,
		if(actiune.contentEquals("2") && tip_comanda.contentEquals("A")) {
			
			 //monitorizare selectie curenta
			 this.setCurrent_selection(tema2_ISP.Categorie_Oferta.RezervareBiletAvion);
			 
			 
			 Enumeration<tema2_ISP.OferteBiletAvion> enumobject = oferteVizualizateBiletAvion.elements();  
		     int index = 0;
		     tema2_ISP.OferteBiletAvion oferta_selectata = null;
		     while (enumobject.hasMoreElements())   
		     {             
		    	if(enumobject.nextElement().getCod_oferta().contentEquals(cod_oferta.trim())) {
		    		oferta_selectata = oferteVizualizateBiletAvion.get(index);
		    	}
				index++;
		     }
		     
		     this.plata_comandaAvion(oferta_selectata);
		     oferta_selectata.generareDetaliiIncluse();
		}
		if(actiune.contentEquals("1") && tip_comanda.contentEquals("A")) {
			 
			 //monitorizare selectie curenta
			this.setCurrent_selection(tema2_ISP.Categorie_Oferta.RezervareBiletAvion);
			
			Enumeration<tema2_ISP.OferteBiletAvion> enumobject = oferteVizualizateBiletAvion.elements();  
			 int index = 0;
		     while (enumobject.hasMoreElements())   
		     {             
		    	if(enumobject.nextElement().getCod_oferta().contentEquals(cod_oferta.trim())) {
		    		oferteVizualizateBiletAvion.get(index).generareDetaliiIncluse();
		    	}
		    	index++;
		     }
		}
		//1H,2H,
		if(actiune.contentEquals("2") && tip_comanda.contentEquals("H")) {
			
			 //monitorizare selectie curenta
			 this.setCurrent_selection(tema2_ISP.Categorie_Oferta.SejurHotel);
			 
			 Enumeration<tema2_ISP.OferteSejurHotel> enumobject = oferteVizualizateSejurHotel.elements();  
		     int index = 0;
		     tema2_ISP.OferteSejurHotel oferta_selectata = null;
		     while (enumobject.hasMoreElements())   
		     {             
		    	if(enumobject.nextElement().getCod_oferta().contentEquals(cod_oferta.trim())) {
		    		oferta_selectata = oferteVizualizateSejurHotel.get(index);
		    	}
				index++;
		     }
				
		     this.plata_comandaSejurHotel(oferta_selectata);	
		     oferta_selectata.generareDetaliiIncluse();
		}
		if(actiune.contentEquals("1") && tip_comanda.contentEquals("H")) {
			
			 //monitorizare selectie curenta
			 this.setCurrent_selection(tema2_ISP.Categorie_Oferta.SejurHotel);
			 
			 Enumeration<tema2_ISP.OferteSejurHotel> enumobject = oferteVizualizateSejurHotel.elements();  
			 int index = 0;
		     while (enumobject.hasMoreElements())   
		     {             
		    	if(enumobject.nextElement().getCod_oferta().contentEquals(cod_oferta.trim())) {
		    		oferteVizualizateSejurHotel.get(index).generareDetaliiIncluse();
		    	}
		    	index++;
		     }
		}
		//1M,2M
		if(actiune.contentEquals("2") && tip_comanda.contentEquals("M")) {
			 //monitorizare selectie curenta
			 this.setCurrent_selection(tema2_ISP.Categorie_Oferta.InchiriereMasina);
			 
			 Enumeration<tema2_ISP.OferteMasini> enumobject = oferteVizualizateMasini.elements();  
		     int index = 0;
		     tema2_ISP.OferteMasini oferta_selectata = null;
		     while (enumobject.hasMoreElements())   
		     {             
		    	if(enumobject.nextElement().getCod_oferta().contentEquals(cod_oferta.trim())) {
		    		oferta_selectata = oferteVizualizateMasini.get(index);
		    	}
				index++;
		     }
				
		     this.plata_comandaMasina(oferta_selectata);
		     oferta_selectata.generareDetaliiIncluse();
		}
		if(actiune.contentEquals("1") && tip_comanda.contentEquals("M")) {
			 //monitorizare selectie curenta
			 this.setCurrent_selection(tema2_ISP.Categorie_Oferta.InchiriereMasina); 
			
			
			Enumeration<tema2_ISP.OferteMasini> enumobject = oferteVizualizateMasini.elements();  
			 int index = 0;
		     while (enumobject.hasMoreElements())   
		     {             
		    	if(enumobject.nextElement().getCod_oferta().contentEquals(cod_oferta.trim())) {
		    		oferteVizualizateMasini.get(index).generareDetaliiIncluse();
		    	}
		    	index++;
		     }
		}
		
	}
	
	//PENTRU ADUAGAREA REZERVARILOR DE MASINI 
	public static Vector<tema2_ISP.RezervariMasini> rezervariMasini = new Vector<tema2_ISP.RezervariMasini>();
	public void rezervareMasina(tema2_ISP.OferteMasini o_masina, String cod_comanda) {
		tema2_ISP.RezervariMasini rezervareM= new tema2_ISP.RezervariMasini(o_masina, this, cod_comanda);
		rezervariMasini.add(rezervareM);
	}
	
	//PENTRU ADAUGAREA REZERVARILOR DE HOTEL
	public static Vector<tema2_ISP.RezervariHotel> rezervariHotel = new Vector<tema2_ISP.RezervariHotel>();
	public void rezervareHotel(tema2_ISP.OferteSejurHotel o_hotel, String cod_comanda) {	
		tema2_ISP.RezervariHotel rezervareH =new tema2_ISP.RezervariHotel(o_hotel, this, cod_comanda);
		rezervariHotel.add(rezervareH);
	}
	
	//PENTRU ADUAGAREA REZERVARILOR DE BILET AVION
	public static Vector<tema2_ISP.RezervariBiletAvion> rezervariAvion= new Vector<tema2_ISP.RezervariBiletAvion>();
	public void rezervareAvion(tema2_ISP.OferteBiletAvion o_avion, String cod_comanda) {	
		tema2_ISP.RezervariBiletAvion rezervareA = new tema2_ISP.RezervariBiletAvion(o_avion, this, cod_comanda);
		rezervariAvion.add(rezervareA);
	}
	
	public void vizualizareIstoricRezervari() {
		System.out.println("1.Rezervari masini");
		System.out.println("2.Rezervari bilete de avion");
		System.out.println("3.Rezervari sejur hotel");
		String optiune = "";
		System.out.println("Introduceti tipul rezervare:");
		Scanner scanner = new Scanner(System.in);
		optiune = scanner.nextLine();
		switch(optiune) {
			case "2":{
				System.out.println("Rezervari Bilete de avion: ");
				Iterator<tema2_ISP.RezervariBiletAvion> iteratorAvion = rezervariAvion.iterator();
				while (iteratorAvion.hasNext()) {
				   iteratorAvion.next().getOferta().generareDetaliiIncluse();
				}
				break;
			}
			case "3":{
				System.out.println("Rezervari sejur hotel: ");
				Iterator<tema2_ISP.RezervariHotel> iteratorHotel = rezervariHotel.iterator();
				while (iteratorHotel.hasNext()) {
					iteratorHotel.next().getOferta_hotel().generareDetaliiIncluse();
				}
				break;
				
			}
			case "1":{
				System.out.println("Rezervari masini: ");
				Iterator<tema2_ISP.RezervariMasini> iteratorMasini = rezervariMasini.iterator();
				while (iteratorMasini.hasNext()) {
					iteratorMasini.next().getOferta_masina().generareDetaliiIncluse();
				}
				break;
			}
		}	
	}
	
	public void plata_comandaAvion(OferteBiletAvion bilet) {
		System.out.println("Cate bilete la aceasta oferta doriti?");
		String nrBilete = "";
		Scanner scanner = new Scanner(System.in);
		nrBilete = scanner.nextLine();
		//PLATA BILETE AVION SI REALIZARE REZERVARE
        System.out.print("Acesta este ultimul pas al rezervarii! Doriti sa continuati crearea rezervãrii in valoare de :");
        System.out.print(Float.parseFloat(nrBilete)*bilet.Pret);
        System.out.print(" ?[y/n]");
        String com = "";
		com = scanner.nextLine();
		if(com.contentEquals("y")) {
			System.out.println("Comanda in valoare de : ");
			System.out.print(Float.parseFloat(nrBilete)*bilet.Pret);
			System.out.print("a fost realizata cu succes si va fi inregistrata in sistem.");
			System.out.println("Cantitate: "+nrBilete);
			bilet.generareDetaliiIncluse();
			//FORMARE COD_COMANDA SI ASOCIERE CU REZERVARE DOAR DACA CLIENTUL ESTE LOGAT
			if(super.logat == true) {
				String cod_comanda = bilet.getCod_oferta()+bilet.getDestinatie().charAt(0)+nrBilete;
				this.setPret_comanda_curenta(Float.parseFloat(nrBilete)*bilet.Pret);
				System.out.println("Rezervare in curs de inregistrare...");
				if(bilet.getStoc()!=0) {
					this.rezervareAvion(bilet, cod_comanda);
					//O Rezervare cu clientul,oferta solicitata, comanda_dorita(nrBilete sau chestii) ,tipul de comanda, codul comenzii
					tema2_ISP.Rezervari rezervare_noua = new Rezervari(this, bilet, cod_comanda,tema2_ISP.Categorie_Oferta.RezervareBiletAvion,Integer.parseInt(nrBilete));
					tema2_ISP.AgentTurism.rezervari.add(rezervare_noua);
				}
				else {
					System.err.println("Stoc indisponibil!");
					this.error_status = "Stoc indisponibil!";
				}
			}
			else {
				System.err.println("Ati incercat sa realizati o comanda fara sa fiti logat!");
				this.error_status = "Ati incercat sa realizati o comanda fara sa fiti logat!";
			}
		}
		else {
			super.logout();
		}
	}
	
	public void plata_comandaMasina(OferteMasini oferta_masina) {
		System.out.println("Pentru cate ore veti inchiria masina?");
		String nrOre = "";
		Scanner scanner = new Scanner(System.in);
		nrOre = scanner.nextLine();
		//PLATA MASINA SI REALIZARE REZERVARE
		System.out.println("Acesta este ultimul pas al rezervarii! Doriti sa abandonati sau sa creati rezervarea in valoare de :");
		System.out.print(Float.parseFloat(nrOre)*oferta_masina.Pret);
		System.out.print("?[y/n]");
		
		String com = "";
		com = scanner.nextLine();
		if(com.contentEquals("y")) {
			System.out.print("Comanda in valoare de : ");
			System.out.print(Float.parseFloat(nrOre)*oferta_masina.Pret);
			System.out.print("a fost realizata cu succes si va fi inregistrata in sistem.");
			oferta_masina.generareDetaliiIncluse();
			System.out.println("Durata sejur: "+nrOre);
			//FORMARE COD_COMANDA SI ASOCIERE CU REZERVARE
			String cod_comanda = "";
			if(super.logat == true) {
				cod_comanda = oferta_masina.getCod_oferta()+oferta_masina.getMarca().charAt(0)+nrOre;
				this.setPret_comanda_curenta(Float.parseFloat(nrOre)*oferta_masina.Pret);
				System.out.println("Rezervare in curs de inregistrare...");
				if(oferta_masina.getStoc()!=0) {
					this.rezervareMasina(oferta_masina, cod_comanda);
					//dupa ce s-a terminat sesiunea de rezervare, actualizam registrul de rezervari vizualizat de 
					tema2_ISP.Rezervari rezervare_noua = new Rezervari(this, oferta_masina, cod_comanda,tema2_ISP.Categorie_Oferta.InchiriereMasina,1);
					tema2_ISP.AgentTurism.rezervari.add(rezervare_noua);
				}
				else {
					System.err.println("Stoc indisponibil!");
				}
			}
			else {
				System.err.println("Ati incercat sa realizati o rezervare fara a fi logat");
			}
		}
		else {
			super.logout();
		}
	}
	public void plata_comandaSejurHotel(OferteSejurHotel sejur) {
		System.out.println("Pentru cate zile veti face rezervare?");
		Scanner scanner = new Scanner(System.in);
		String nrZile = "";
		nrZile = scanner.nextLine();
		//PLATA MASINA SI REALIZARE REZERVARE
		System.out.println("Acesta este ultimul pas al rezervarii! Doriti sa abandonati sau sa creati rezervarea in valoare de :");
		System.out.print(Float.parseFloat(nrZile)*sejur.Pret);
		System.out.print("?[y/n]");
		String com = "";
		com = scanner.nextLine();
		if(com.contentEquals("y")) {
			System.out.print("Comanda in valoare de : ");
			System.out.print(Float.parseFloat(nrZile)*sejur.Pret);
			System.out.print("a fost realizata cu succes si va fi inregistrata in sistem.");
			sejur.generareDetaliiIncluse();
			System.out.println("Durata sejur: "+nrZile);
			//FORMARE COD_COMANDA, SETRE PRET COMANDA SI ASOCIERE CU REZERVARE
			if(super.logat == true) {
				String cod_comanda = sejur.getCod_oferta()+sejur.getLocatie().charAt(0)+nrZile;
				this.setPret_comanda_curenta(Float.parseFloat(nrZile)*sejur.Pret);
				System.out.println("Rezervare in curs de inregistrare...");
				if(sejur.getStoc()!=0) {
					this.rezervareHotel(sejur, cod_comanda);
					tema2_ISP.Rezervari rezervare_noua = new Rezervari(this, sejur, cod_comanda,tema2_ISP.Categorie_Oferta.SejurHotel,1);
					tema2_ISP.AgentTurism.rezervari.add(rezervare_noua);
				}
				else {
					System.err.println("Stoc indisponibil!");
				}
			}
			else {
				System.err.println("Ati incercat sa realizati o comanda fara a fi logat!");
			}
		}
		else {
			super.logout();
		}
	}

	public float getPret_comanda_curenta() {
		return pret_comanda_curenta;
	}

	public void setPret_comanda_curenta(float pret_comanda_curenta) {
		this.pret_comanda_curenta = pret_comanda_curenta;
	}

	public tema2_ISP.Categorie_Oferta getCurrent_selection() {
		return current_selection;
	}

	public void setCurrent_selection(tema2_ISP.Categorie_Oferta current_selection) {
		this.current_selection = current_selection;
	}

	public String getDestinatie_curenta() {
		return destinatie_curenta;
	}

	public void setDestinatie_curenta(String destinatie_curenta) {
		this.destinatie_curenta = destinatie_curenta;
	}
};
