// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

/************************************************************/
/**
 * 
 */
public class OferteSejurHotel extends tema2_ISP.Oferte {
	OferteSejurHotel(tema2_ISP.Categorie_Oferta categorie, String detalii_oferta) {
		super(categorie, detalii_oferta);
		// TODO Auto-generated constructor stub
	}

	public String getUnitate_pret() {
		return unitate_pret;
	}

	public void setUnitate_pret(String unitate_pret) {
		this.unitate_pret = unitate_pret;
	}

	public String getTipCamera() {
		return TipCamera;
	}

	public void setTipCamera(String tipCamera) {
		TipCamera = tipCamera;
	}

	public String getFacilitati() {
		return Facilitati;
	}

	public void setFacilitati(String facilitati) {
		Facilitati = facilitati;
	}

	public float getPret_unitar() {
		return super.Pret;
	}
	
	public void setLocatie(String loc) {
		this.locatieHotel = loc;
	}
	public String getLocatie() {
		return locatieHotel;
	}
	/**
	 * 
	 */
	private String unitate_pret = "Zi";
	private String TipCamera;
	private String Facilitati;
	private String locatieHotel;
};
