// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

import java.time.LocalDate;
/************************************************************/
/**
 * 
 */
public class Rezervari {
				/**
				 * 
				 */
				private static int nrRezervare = 0;
				
				private String cod_comanda;
				
				private String tip_comanda;
				
				private tema2_ISP.Client client;
				
				private tema2_ISP.Oferte oferta_solicitata;
				
				private int cantitate_solicitata;
				
				public LocalDate data_comanda;
				
				private boolean validata;
				
				public Rezervari(tema2_ISP.Client c, tema2_ISP.Oferte oferta_selectata, String cod_comanda, tema2_ISP.Categorie_Oferta categorie ,int cantitate){
					//incrementare nrRezervare
					this.setNrRezervare(this.getNrRezervare()+1);
					//setare tip comanda
					if(categorie == tema2_ISP.Categorie_Oferta.InchiriereMasina);
						this.setTip_comanda("M");
					if(categorie == tema2_ISP.Categorie_Oferta.SejurHotel);
						this.setTip_comanda("A");
					if(categorie == tema2_ISP.Categorie_Oferta.RezervareBiletAvion);
						this.setTip_comanda("H");
					//Asociem codul de comanda
					this.setCod_comanda(cod_comanda);
					//asociem clientul, respectiv automat cu alegerile sale de comenzi 
					this.set_comanda_client(c);
					//monitorizare oferta selectata pentru compoarare ulterioara stoc + validare
					this.oferta_solicitata = oferta_selectata;
					//setare cantitate comanda
					this.setCantitate_solicitata(cantitate);
					LocalDate localDate = LocalDate.now();
			        data_comanda = localDate;
					//System.out.println(this.getNrRezervare());
				}
				
				public void set_comanda_client(Client c) {
					this.client = c;
				}
				public tema2_ISP.Client get_comanda_client() {
					return client;
				}

				
				
				public int getNrRezervare() {
					return nrRezervare;
				}
				public void setNrRezervare(int nrRezervare) {
					Rezervari.nrRezervare = nrRezervare;
				}
				public String getCod_comanda() {
					return cod_comanda;
				}
				public void setCod_comanda(String cod_comanda) {
					this.cod_comanda = cod_comanda;
				}
				public boolean isValidata() {
					return validata;
				}
				public void setValidata(boolean validata) {
					this.validata = validata;
				}
				public String getTip_comanda() {
					return tip_comanda;
				}
				public void setTip_comanda(String tip_comanda) {
					this.tip_comanda = tip_comanda;
				}

				public tema2_ISP.Oferte getOferta_solicitata() {
					return oferta_solicitata;
				}

				public void setOferta_solicitata(tema2_ISP.Oferte oferta_solicitata) {
					this.oferta_solicitata = oferta_solicitata;
				}

				public int getCantitate_solicitata() {
					return cantitate_solicitata;
				}

				public void setCantitate_solicitata(int cantitate_solicitata) {
					this.cantitate_solicitata = cantitate_solicitata;
				}
};
